using System;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace EasyJudoClub.Model
{
    static class CommunesHelper
    {
        public static int GetCodePostal(string commune)
        {
            return CommuneCodePostal.FirstOrDefault(x => String.Compare(x.Key, commune, true) == 0).Value;
        }

        public static List<string> GetAllCommunes()
        {
            return CommuneCodePostal.Select(x => x.Key.ToString()).ToList();
        }
        
        public static List<string> GetCommunes(string codePostal)
        {
            return String.IsNullOrEmpty(codePostal)? GetAllCommunes() : CommuneCodePostal.Where(x => x.Value.ToString().Contains(codePostal)).Select(x => x.Key).ToList();
        }

        public static List<KeyValuePair<string, int>> CommuneCodePostal = new List<KeyValuePair<string, int>>(){
                new KeyValuePair<string, int>("Les Abrets",38490),
                new KeyValuePair<string, int>("Les Abrets",38490),
                new KeyValuePair<string, int>("Les Adrets",38190),
                new KeyValuePair<string, int>("Agnin",38150),
                new KeyValuePair<string, int>("L'Albenc",38470),
                new KeyValuePair<string, int>("Allemond",38114),
                new KeyValuePair<string, int>("Allevard",38580),
                new KeyValuePair<string, int>("Ambel",38970),
                new KeyValuePair<string, int>("Anjou",38150),
                new KeyValuePair<string, int>("Annoisin-Chatelans",38460),
                new KeyValuePair<string, int>("Anthon",38280),
                new KeyValuePair<string, int>("Aoste",38490),
                new KeyValuePair<string, int>("Apprieu",38140),
                new KeyValuePair<string, int>("Arandon",38510),
                new KeyValuePair<string, int>("Artas",38440),
                new KeyValuePair<string, int>("Arzay",38260),
                new KeyValuePair<string, int>("Assieu",38150),
                new KeyValuePair<string, int>("Auberives-en-Royans",38680),
                new KeyValuePair<string, int>("Auberives-sur-Varèze",38550),
                new KeyValuePair<string, int>("Auris",38142),
                new KeyValuePair<string, int>("Autrans",38880),
                new KeyValuePair<string, int>("Les Avenières",38630),
                new KeyValuePair<string, int>("Avignonet",38650),
                new KeyValuePair<string, int>("Badinières",38300),
                new KeyValuePair<string, int>("Balbins",38260),
                new KeyValuePair<string, int>("La Balme-les-Grottes",38390),
                new KeyValuePair<string, int>("Barraux",38530),
                new KeyValuePair<string, int>("La Bâtie-Divisin",38490),
                new KeyValuePair<string, int>("La Bâtie-Montgascon",38110),
                new KeyValuePair<string, int>("Beaucroissant",38140),
                new KeyValuePair<string, int>("Beaufin",38970),
                new KeyValuePair<string, int>("Beaufort",38270),
                new KeyValuePair<string, int>("Beaulieu",38470),
                new KeyValuePair<string, int>("Beaurepaire",38270),
                new KeyValuePair<string, int>("Beauvoir-de-Marc",38440),
                new KeyValuePair<string, int>("Beauvoir-en-Royans",38160),
                new KeyValuePair<string, int>("Bellegarde-Poussieu",38270),
                new KeyValuePair<string, int>("Belmont",38690),
                new KeyValuePair<string, int>("Bernin",38190),
                new KeyValuePair<string, int>("Besse",38142),
                new KeyValuePair<string, int>("Bessins",38160),
                new KeyValuePair<string, int>("Bévenais",38690),
                new KeyValuePair<string, int>("Bilieu",38850),
                new KeyValuePair<string, int>("Biol",38690),
                new KeyValuePair<string, int>("Biviers",38330),
                new KeyValuePair<string, int>("Bizonnes",38690),
                new KeyValuePair<string, int>("Blandin",38730),
                new KeyValuePair<string, int>("Bonnefamille",38090),
                new KeyValuePair<string, int>("Bossieu",38260),
                new KeyValuePair<string, int>("Le Bouchage",38510),
                new KeyValuePair<string, int>("Bougé-Chambalud",38150),
                new KeyValuePair<string, int>("Le Bourg-d'Oisans",38520),
                new KeyValuePair<string, int>("Bourgoin-Jallieu",38300),
                new KeyValuePair<string, int>("Bouvesse-Quirieu",38390),
                new KeyValuePair<string, int>("Brangues",38510),
                new KeyValuePair<string, int>("Bressieux",38870),
                new KeyValuePair<string, int>("Bresson",38320),
                new KeyValuePair<string, int>("Brézins",38590),
                new KeyValuePair<string, int>("Brié-et-Angonnes",38320),
                new KeyValuePair<string, int>("Brion",38590),
                new KeyValuePair<string, int>("La Buisse",38500),
                new KeyValuePair<string, int>("La Buissière",38530),
                new KeyValuePair<string, int>("Burcin",38690),
                new KeyValuePair<string, int>("Cessieu",38110),
                new KeyValuePair<string, int>("Châbons",38690),
                new KeyValuePair<string, int>("Châlons",38122),
                new KeyValuePair<string, int>("Chamagnieu",38460),
                new KeyValuePair<string, int>("Champagnier",38800),
                new KeyValuePair<string, int>("Champier",38260),
                new KeyValuePair<string, int>("Le Champ-près-Froges",38190),
                new KeyValuePair<string, int>("Champ-sur-Drac",38560),
                new KeyValuePair<string, int>("Chamrousse",38410),
                new KeyValuePair<string, int>("Chanas",38150),
                new KeyValuePair<string, int>("Chantelouve",38740),
                new KeyValuePair<string, int>("Chantesse",38470),
                new KeyValuePair<string, int>("Chapareillan",38530),
                new KeyValuePair<string, int>("La Chapelle-de-la-Tour",38110),
                new KeyValuePair<string, int>("La Chapelle-de-Surieu",38150),
                new KeyValuePair<string, int>("La Chapelle-du-Bard",38580),
                new KeyValuePair<string, int>("Charancieu",38490),
                new KeyValuePair<string, int>("Charantonnay",38790),
                new KeyValuePair<string, int>("Charavines",38850),
                new KeyValuePair<string, int>("Charette",38390),
                new KeyValuePair<string, int>("Charnècles",38140),
                new KeyValuePair<string, int>("Charvieu-Chavagneux",38230),
                new KeyValuePair<string, int>("Chasselay",38470),
                new KeyValuePair<string, int>("Chasse-sur-Rhône",38670),
                new KeyValuePair<string, int>("Chassignieu",38730),
                new KeyValuePair<string, int>("Château-Bernard",38650),
                new KeyValuePair<string, int>("Châteauvilain",38300),
                new KeyValuePair<string, int>("Châtelus",38680),
                new KeyValuePair<string, int>("Châtenay",38980),
                new KeyValuePair<string, int>("Châtonnay",38440),
                new KeyValuePair<string, int>("Chatte",38160),
                new KeyValuePair<string, int>("Chavanoz",38230),
                new KeyValuePair<string, int>("Chélieu",38730),
                new KeyValuePair<string, int>("Chevrières",38160),
                new KeyValuePair<string, int>("Le Cheylas",38570),
                new KeyValuePair<string, int>("Cheyssieu",38550),
                new KeyValuePair<string, int>("Chèzeneuve",38300),
                new KeyValuePair<string, int>("Chichilianne",38930),
                new KeyValuePair<string, int>("Chimilin",38490),
                new KeyValuePair<string, int>("Chirens",38850),
                new KeyValuePair<string, int>("Cholonge",38220),
                new KeyValuePair<string, int>("Chonas-l'Amballan",38121),
                new KeyValuePair<string, int>("Choranche",38680),
                new KeyValuePair<string, int>("Chozeau",38460),
                new KeyValuePair<string, int>("Chuzelles",38200),
                new KeyValuePair<string, int>("Claix",38640),
                new KeyValuePair<string, int>("Clavans-en-Haut-Oisans",38142),
                new KeyValuePair<string, int>("Clelles",38930),
                new KeyValuePair<string, int>("Clonas-sur-Varèze",38550),
                new KeyValuePair<string, int>("Cognet",38350),
                new KeyValuePair<string, int>("Cognin-les-Gorges",38470),
                new KeyValuePair<string, int>("Colombe",38690),
                new KeyValuePair<string, int>("La Combe-de-Lancey",38190),
                new KeyValuePair<string, int>("Commelle",38260),
                new KeyValuePair<string, int>("Corbelin",38630),
                new KeyValuePair<string, int>("Cordéac",38710),
                new KeyValuePair<string, int>("Corenc",38700),
                new KeyValuePair<string, int>("Cornillon-en-Trièves",38710),
                new KeyValuePair<string, int>("Corps",38970),
                new KeyValuePair<string, int>("Corrençon-en-Vercors",38250),
                new KeyValuePair<string, int>("La Côte-Saint-André",38260),
                new KeyValuePair<string, int>("Les Côtes-d'Arey",38138),
                new KeyValuePair<string, int>("Les Côtes-de-Corps",38970),
                new KeyValuePair<string, int>("Coublevie",38500),
                new KeyValuePair<string, int>("Cour-et-Buis",38122),
                new KeyValuePair<string, int>("Courtenay",38510),
                new KeyValuePair<string, int>("Crachier",38300),
                new KeyValuePair<string, int>("Cras",38210),
                new KeyValuePair<string, int>("Crémieu",38460),
                new KeyValuePair<string, int>("Creys-Mépieu",38510),
                new KeyValuePair<string, int>("Crolles",38920),
                new KeyValuePair<string, int>("Culin",38300),
                new KeyValuePair<string, int>("Diémoz",38790),
                new KeyValuePair<string, int>("Dionay",38160),
                new KeyValuePair<string, int>("Dizimieu",38460),
                new KeyValuePair<string, int>("Doissin",38730),
                new KeyValuePair<string, int>("Dolomieu",38110),
                new KeyValuePair<string, int>("Domarin",38300),
                new KeyValuePair<string, int>("Domène",38420),
                new KeyValuePair<string, int>("Échirolles",38130),
                new KeyValuePair<string, int>("Eclose",38300),
                new KeyValuePair<string, int>("Engins",38360),
                new KeyValuePair<string, int>("Entraigues",38740),
                new KeyValuePair<string, int>("Entre-deux-Guiers",38380),
                new KeyValuePair<string, int>("Les Éparres",38300),
                new KeyValuePair<string, int>("Estrablin",38780),
                new KeyValuePair<string, int>("Eybens",38320),
                new KeyValuePair<string, int>("Eydoche",38690),
                new KeyValuePair<string, int>("Eyzin-Pinet",38780),
                new KeyValuePair<string, int>("Faramans",38260),
                new KeyValuePair<string, int>("Faverges-de-la-Tour",38110),
                new KeyValuePair<string, int>("La Ferrière",38580),
                new KeyValuePair<string, int>("Fitilieu",38490),
                new KeyValuePair<string, int>("La Flachère",38530),
                new KeyValuePair<string, int>("Flachères",38690),
                new KeyValuePair<string, int>("Fontaine",38600),
                new KeyValuePair<string, int>("Fontanil-Cornillon",38120),
                new KeyValuePair<string, int>("La Forteresse",38590),
                new KeyValuePair<string, int>("Four",38080),
                new KeyValuePair<string, int>("Le Freney-d'Oisans",38142),
                new KeyValuePair<string, int>("La Frette",38260),
                new KeyValuePair<string, int>("Froges",38190),
                new KeyValuePair<string, int>("Frontonas",38290),
                new KeyValuePair<string, int>("La Garde",38520),
                new KeyValuePair<string, int>("Gières",38610),
                new KeyValuePair<string, int>("Gillonnay",38260),
                new KeyValuePair<string, int>("Goncelin",38570),
                new KeyValuePair<string, int>("Le Grand-Lemps",38690),
                new KeyValuePair<string, int>("Granieu",38490),
                new KeyValuePair<string, int>("Grenay",38540),
                new KeyValuePair<string, int>("Grenoble",38000),
                new KeyValuePair<string, int>("",38100),
                new KeyValuePair<string, int>("Gresse-en-Vercors",38650),
                new KeyValuePair<string, int>("Le Gua",38450),
                new KeyValuePair<string, int>("Herbeys",38320),
                new KeyValuePair<string, int>("Heyrieux",38540),
                new KeyValuePair<string, int>("Hières-sur-Amby",38118),
                new KeyValuePair<string, int>("Huez",38750),
                new KeyValuePair<string, int>("Hurtières",38570),
                new KeyValuePair<string, int>("L'Isle-d'Abeau",38080),
                new KeyValuePair<string, int>("Izeaux",38140),
                new KeyValuePair<string, int>("Izeron",38160),
                new KeyValuePair<string, int>("Janneyrias",38280),
                new KeyValuePair<string, int>("Jarcieu",38270),
                new KeyValuePair<string, int>("Jardin",38200),
                new KeyValuePair<string, int>("Jarrie",38560),
                new KeyValuePair<string, int>("Laffrey",38220),
                new KeyValuePair<string, int>("Lalley",38930),
                new KeyValuePair<string, int>("Lans-en-Vercors",38250),
                new KeyValuePair<string, int>("Laval",38190),
                new KeyValuePair<string, int>("Lavaldens",38350),
                new KeyValuePair<string, int>("Lavars",38710),
                new KeyValuePair<string, int>("Lentiol",38270),
                new KeyValuePair<string, int>("Leyrieu",38460),
                new KeyValuePair<string, int>("Lieudieu",38440),
                new KeyValuePair<string, int>("Livet-et-Gavet",38220),
                new KeyValuePair<string, int>("Longechenal",38690),
                new KeyValuePair<string, int>("Lumbin",38660),
                new KeyValuePair<string, int>("Luzinay",38200),
                new KeyValuePair<string, int>("Malleval-en-Vercors",38470),
                new KeyValuePair<string, int>("Marcieu",38350),
                new KeyValuePair<string, int>("Marcilloles",38260),
                new KeyValuePair<string, int>("Marcollin",38270),
                new KeyValuePair<string, int>("Marnans",38980),
                new KeyValuePair<string, int>("Massieu",38620),
                new KeyValuePair<string, int>("Maubec",38300),
                new KeyValuePair<string, int>("Mayres-Savel",38350),
                new KeyValuePair<string, int>("Méaudre",38112),
                new KeyValuePair<string, int>("Mens",38710),
                new KeyValuePair<string, int>("Merlas",38620),
                new KeyValuePair<string, int>("Meylan",38240),
                new KeyValuePair<string, int>("Meyrié",38300),
                new KeyValuePair<string, int>("Meyrieu-les-Étangs",38440),
                new KeyValuePair<string, int>("Meyssiès",38440),
                new KeyValuePair<string, int>("Miribel-Lanchâtre",38450),
                new KeyValuePair<string, int>("Miribel-les-Échelles",38380),
                new KeyValuePair<string, int>("Mizoën",38142),
                new KeyValuePair<string, int>("Moidieu-Détourbe",38440),
                new KeyValuePair<string, int>("Moirans",38430),
                new KeyValuePair<string, int>("Moissieu-sur-Dolon",38270),
                new KeyValuePair<string, int>("Monestier-d'Ambel",38970),
                new KeyValuePair<string, int>("Monestier-de-Clermont",38650),
                new KeyValuePair<string, int>("Le Monestier-du-Percy",38930),
                new KeyValuePair<string, int>("Monsteroux-Milieu",38122),
                new KeyValuePair<string, int>("Montagne",38160),
                new KeyValuePair<string, int>("Montagnieu",38110),
                new KeyValuePair<string, int>("Montalieu-Vercieu",38390),
                new KeyValuePair<string, int>("Montaud",38210),
                new KeyValuePair<string, int>("Montbonnot-Saint-Martin",38330),
                new KeyValuePair<string, int>("Montcarra",38890),
                new KeyValuePair<string, int>("Montchaboud",38220),
                new KeyValuePair<string, int>("Mont-de-Lans",38860),
                new KeyValuePair<string, int>("Monteynard",38770),
                new KeyValuePair<string, int>("Montfalcon",38940),
                new KeyValuePair<string, int>("Montferrat",38620),
                new KeyValuePair<string, int>("Montrevel",38690),
                new KeyValuePair<string, int>("Mont-Saint-Martin",38120),
                new KeyValuePair<string, int>("Montseveroux",38122),
                new KeyValuePair<string, int>("Moras",38460),
                new KeyValuePair<string, int>("Morestel",38510),
                new KeyValuePair<string, int>("Morêtel-de-Mailles",38570),
                new KeyValuePair<string, int>("Morette",38210),
                new KeyValuePair<string, int>("La Morte",38350),
                new KeyValuePair<string, int>("La Motte-d'Aveillans",38770),
                new KeyValuePair<string, int>("La Motte-Saint-Martin",38770),
                new KeyValuePair<string, int>("Mottier",38260),
                new KeyValuePair<string, int>("Le Moutaret",38580),
                new KeyValuePair<string, int>("La Mure",38350),
                new KeyValuePair<string, int>("La Murette",38140),
                new KeyValuePair<string, int>("Murianette",38420),
                new KeyValuePair<string, int>("Murinais",38160),
                new KeyValuePair<string, int>("Nantes-en-Ratier",38350),
                new KeyValuePair<string, int>("Nantoin",38260),
                new KeyValuePair<string, int>("Nivolas-Vermelle",38300),
                new KeyValuePair<string, int>("Notre-Dame-de-Commiers",38450),
                new KeyValuePair<string, int>("Notre-Dame-de-l'Osier",38470),
                new KeyValuePair<string, int>("Notre-Dame-de-Mésage",38220),
                new KeyValuePair<string, int>("Notre-Dame-de-Vaulx",38144),
                new KeyValuePair<string, int>("Noyarey",38360),
                new KeyValuePair<string, int>("Optevoz",38460),
                new KeyValuePair<string, int>("Oris-en-Rattier",38350),
                new KeyValuePair<string, int>("Ornacieux",38260),
                new KeyValuePair<string, int>("Ornon",38520),
                new KeyValuePair<string, int>("Oulles",38520),
                new KeyValuePair<string, int>("Oyeu",38690),
                new KeyValuePair<string, int>("Oytier-Saint-Oblas",38780),
                new KeyValuePair<string, int>("Oz",38114),
                new KeyValuePair<string, int>("Pact",38270),
                new KeyValuePair<string, int>("Pajay",38260),
                new KeyValuePair<string, int>("Paladru",38850),
                new KeyValuePair<string, int>("Panissage",38730),
                new KeyValuePair<string, int>("Panossas",38460),
                new KeyValuePair<string, int>("Parmilieu",38390),
                new KeyValuePair<string, int>("Le Passage",38490),
                new KeyValuePair<string, int>("Passins",38510),
                new KeyValuePair<string, int>("Le Péage-de-Roussillon",38550),
                new KeyValuePair<string, int>("Pellafol",38970),
                new KeyValuePair<string, int>("Penol",38260),
                new KeyValuePair<string, int>("Percy",38930),
                new KeyValuePair<string, int>("Le Périer",38740),
                new KeyValuePair<string, int>("La Pierre",38570),
                new KeyValuePair<string, int>("Pierre-Châtel",38119),
                new KeyValuePair<string, int>("Le Pin",38730),
                new KeyValuePair<string, int>("Pinsot",38580),
                new KeyValuePair<string, int>("Pisieu",38270),
                new KeyValuePair<string, int>("Plan",38590),
                new KeyValuePair<string, int>("Poisat",38320),
                new KeyValuePair<string, int>("Poliénas",38210),
                new KeyValuePair<string, int>("Pommier-de-Beaurepaire",38260),
                new KeyValuePair<string, int>("Pommiers-la-Placette",38340),
                new KeyValuePair<string, int>("Ponsonnas",38350),
                new KeyValuePair<string, int>("Pontcharra",38530),
                new KeyValuePair<string, int>("Pont-de-Beauvoisin",38480),
                new KeyValuePair<string, int>("Pont-de-Chéruy",38230),
                new KeyValuePair<string, int>("Pont-de-Claix",38800),
                new KeyValuePair<string, int>("Pont-en-Royans",38680),
                new KeyValuePair<string, int>("Pont-Évêque",38780),
                new KeyValuePair<string, int>("Porcieu-Amblagnieu",38390),
                new KeyValuePair<string, int>("Prébois",38710),
                new KeyValuePair<string, int>("Presles",38680),
                new KeyValuePair<string, int>("Pressins",38480),
                new KeyValuePair<string, int>("Primarette",38270),
                new KeyValuePair<string, int>("Proveysieux",38120),
                new KeyValuePair<string, int>("Prunières",38350),
                new KeyValuePair<string, int>("Quaix-en-Chartreuse",38950),
                new KeyValuePair<string, int>("Quet-en-Beaumont",38970),
                new KeyValuePair<string, int>("Quincieu",38470),
                new KeyValuePair<string, int>("Réaumont",38140),
                new KeyValuePair<string, int>("Renage",38140),
                new KeyValuePair<string, int>("Rencurel",38680),
                new KeyValuePair<string, int>("Revel",38420),
                new KeyValuePair<string, int>("Revel-Tourdan",38270),
                new KeyValuePair<string, int>("Reventin-Vaugris",38121),
                new KeyValuePair<string, int>("Rives",38140),
                new KeyValuePair<string, int>("La Rivière",38210),
                new KeyValuePair<string, int>("Roche",38090),
                new KeyValuePair<string, int>("Les Roches-de-Condrieu",38370),
                new KeyValuePair<string, int>("Rochetoirin",38110),
                new KeyValuePair<string, int>("Roissard",38650),
                new KeyValuePair<string, int>("Romagnieu",38480),
                new KeyValuePair<string, int>("Roussillon",38150),
                new KeyValuePair<string, int>("Rovon",38470),
                new KeyValuePair<string, int>("Royas",38440),
                new KeyValuePair<string, int>("Roybon",38940),
                new KeyValuePair<string, int>("Ruy",38300),
                new KeyValuePair<string, int>("Sablons",38550),
                new KeyValuePair<string, int>("Saint-Agnin-sur-Bion",38300),
                new KeyValuePair<string, int>("Saint-Alban-de-Roche",38080),
                new KeyValuePair<string, int>("Saint-Alban-du-Rhône",38370),
                new KeyValuePair<string, int>("Saint-Albin-de-Vaulserre",38480),
                new KeyValuePair<string, int>("Saint-Andéol",38650),
                new KeyValuePair<string, int>("Saint-André-en-Royans",38680),
                new KeyValuePair<string, int>("Saint-André-le-Gaz",38490),
                new KeyValuePair<string, int>("Saint-Antoine-l'Abbaye",38160),
                new KeyValuePair<string, int>("Saint-Appolinard",38160),
                new KeyValuePair<string, int>("Saint-Arey",38350),
                new KeyValuePair<string, int>("Saint-Aupre",38960),
                new KeyValuePair<string, int>("Saint-Barthélemy",38270),
                new KeyValuePair<string, int>("Saint-Barthélemy-de-Séchilienne",38220),
                new KeyValuePair<string, int>("Saint-Baudille-de-la-Tour",38118),
                new KeyValuePair<string, int>("Saint-Baudille-et-Pipet",38710),
                new KeyValuePair<string, int>("Saint-Bernard",38660),
                new KeyValuePair<string, int>("Saint-Blaise-du-Buis",38140),
                new KeyValuePair<string, int>("Saint-Bonnet-de-Chavagne",38840),
                new KeyValuePair<string, int>("Saint-Bueil",38620),
                new KeyValuePair<string, int>("Saint-Cassien",38500),
                new KeyValuePair<string, int>("Saint-Chef",38890),
                new KeyValuePair<string, int>("Saint-Christophe-en-Oisans",38520),
                new KeyValuePair<string, int>("Saint-Christophe-sur-Guiers",38380),
                new KeyValuePair<string, int>("Saint-Clair-de-la-Tour",38110),
                new KeyValuePair<string, int>("Saint-Clair-du-Rhône",38370),
                new KeyValuePair<string, int>("Saint-Clair-sur-Galaure",38940),
                new KeyValuePair<string, int>("Saint-Didier-de-Bizonnes",38690),
                new KeyValuePair<string, int>("Saint-Didier-de-la-Tour",38110),
                new KeyValuePair<string, int>("Sainte-Agnès",38190),
                new KeyValuePair<string, int>("Sainte-Anne-sur-Gervonde",38440),
                new KeyValuePair<string, int>("Sainte-Blandine",38110),
                new KeyValuePair<string, int>("Saint-Égrève",38120),
                new KeyValuePair<string, int>("Sainte-Luce",38970),
                new KeyValuePair<string, int>("Sainte-Marie-d'Alloix",38660),
                new KeyValuePair<string, int>("Sainte-Marie-du-Mont",38660),
                new KeyValuePair<string, int>("Saint-Étienne-de-Crossey",38960),
                new KeyValuePair<string, int>("Saint-Étienne-de-Saint-Geoirs",38590),
                new KeyValuePair<string, int>("Saint-Geoire-en-Valdaine",38620),
                new KeyValuePair<string, int>("Saint-Geoirs",38590),
                new KeyValuePair<string, int>("Saint-Georges-de-Commiers",38450),
                new KeyValuePair<string, int>("Saint-Georges-d'Espéranche",38790),
                new KeyValuePair<string, int>("Saint-Gervais",38470),
                new KeyValuePair<string, int>("Saint-Guillaume",38650),
                new KeyValuePair<string, int>("Saint-Hilaire",38660),
                new KeyValuePair<string, int>("Saint-Hilaire-de-Brens",38460),
                new KeyValuePair<string, int>("Saint-Hilaire-de-la-Côte",38260),
                new KeyValuePair<string, int>("Saint-Hilaire-du-Rosier",38840),
                new KeyValuePair<string, int>("Saint-Honoré",38350),
                new KeyValuePair<string, int>("Saint-Ismier",38330),
                new KeyValuePair<string, int>("Saint-Jean-d'Avelanne",38480),
                new KeyValuePair<string, int>("Saint-Jean-de-Bournay",38440),
                new KeyValuePair<string, int>("Saint-Jean-de-Moirans",38430),
                new KeyValuePair<string, int>("Saint-Jean-de-Soudain",38110),
                new KeyValuePair<string, int>("Saint-Jean-de-Vaulx",38220),
                new KeyValuePair<string, int>("Saint-Jean-d'Hérans",38710),
                new KeyValuePair<string, int>("Saint-Jean-le-Vieux",38420),
                new KeyValuePair<string, int>("Saint-Joseph-de-Rivière",38134),
                new KeyValuePair<string, int>("Saint-Julien-de-l'Herms",38122),
                new KeyValuePair<string, int>("Saint-Julien-de-Raz",38134),
                new KeyValuePair<string, int>("Saint-Just-Chaleyssin",38540),
                new KeyValuePair<string, int>("Saint-Just-de-Claix",38680),
                new KeyValuePair<string, int>("Saint-Lattier",38840),
                new KeyValuePair<string, int>("Saint-Laurent-du-Pont",38380),
                new KeyValuePair<string, int>("Saint-Laurent-en-Beaumont",38350),
                new KeyValuePair<string, int>("Saint-Marcel-Bel-Accueil",38080),
                new KeyValuePair<string, int>("Saint-Marcellin",38160),
                new KeyValuePair<string, int>("Saint-Martin-de-Clelles",38930),
                new KeyValuePair<string, int>("Saint-Martin-de-la-Cluze",38650),
                new KeyValuePair<string, int>("Saint-Martin-de-Vaulserre",38480),
                new KeyValuePair<string, int>("Saint-Martin-d'Hères",38400),
                new KeyValuePair<string, int>("Saint-Martin-d'Uriage",38410),
                new KeyValuePair<string, int>("Saint-Martin-le-Vinoux",38950),
                new KeyValuePair<string, int>("Saint-Maurice-en-Trièves",38930),
                new KeyValuePair<string, int>("Saint-Maurice-l'Exil",38550),
                new KeyValuePair<string, int>("Saint-Maximin",38530),
                new KeyValuePair<string, int>("Saint-Michel-de-Saint-Geoirs",38590),
                new KeyValuePair<string, int>("Saint-Michel-en-Beaumont",38350),
                new KeyValuePair<string, int>("Saint-Michel-les-Portes",38650),
                new KeyValuePair<string, int>("Saint-Mury-Monteymond",38190),
                new KeyValuePair<string, int>("Saint-Nazaire-les-Eymes",38330),
                new KeyValuePair<string, int>("Saint-Nicolas-de-Macherin",38500),
                new KeyValuePair<string, int>("Saint-Nizier-du-Moucherotte",38250),
                new KeyValuePair<string, int>("Saint-Ondras",38490),
                new KeyValuePair<string, int>("Saint-Pancrasse",38660),
                new KeyValuePair<string, int>("Saint-Paul-de-Varces",38760),
                new KeyValuePair<string, int>("Saint-Paul-d'Izeaux",38140),
                new KeyValuePair<string, int>("Saint-Paul-lès-Monestier",38650),
                new KeyValuePair<string, int>("Saint-Pierre-d'Allevard",38830),
                new KeyValuePair<string, int>("Saint-Pierre-de-Bressieux",38870),
                new KeyValuePair<string, int>("Saint-Pierre-de-Chartreuse",38380),
                new KeyValuePair<string, int>("Saint-Pierre-de-Chérennes",38160),
                new KeyValuePair<string, int>("Saint-Pierre-de-Méaroz",38350),
                new KeyValuePair<string, int>("Saint-Pierre-de-Mésage",38220),
                new KeyValuePair<string, int>("Saint-Pierre-d'Entremont",73670),
                new KeyValuePair<string, int>("Saint-Prim",38370),
                new KeyValuePair<string, int>("Saint-Quentin-Fallavier",38070),
                new KeyValuePair<string, int>("Saint-Quentin-sur-Isère",38210),
                new KeyValuePair<string, int>("Saint-Romain-de-Jalionas",38460),
                new KeyValuePair<string, int>("Saint-Romain-de-Surieu",38150),
                new KeyValuePair<string, int>("Saint-Romans",38160),
                new KeyValuePair<string, int>("Saint-Sauveur",38160),
                new KeyValuePair<string, int>("Saint-Savin",38300),
                new KeyValuePair<string, int>("Saint-Sébastien",38710),
                new KeyValuePair<string, int>("Saint-Siméon-de-Bressieux",38870),
                new KeyValuePair<string, int>("Saint-Sorlin-de-Morestel",38510),
                new KeyValuePair<string, int>("Saint-Sorlin-de-Vienne",38200),
                new KeyValuePair<string, int>("Saint-Sulpice-des-Rivoires",38620),
                new KeyValuePair<string, int>("Saint-Théoffrey",38119),
                new KeyValuePair<string, int>("Saint-Vérand",38160),
                new KeyValuePair<string, int>("Saint-Victor-de-Cessieu",38110),
                new KeyValuePair<string, int>("Saint-Victor-de-Morestel",38510),
                new KeyValuePair<string, int>("Saint-Vincent-de-Mercuze",38660),
                new KeyValuePair<string, int>("Salagnon",38890),
                new KeyValuePair<string, int>("Salaise-sur-Sanne",38150),
                new KeyValuePair<string, int>("La Salette-Fallavaux",38970),
                new KeyValuePair<string, int>("La Salle-en-Beaumont",38350),
                new KeyValuePair<string, int>("Le Sappey-en-Chartreuse",38700),
                new KeyValuePair<string, int>("Sarcenas",38700),
                new KeyValuePair<string, int>("Sardieu",38260),
                new KeyValuePair<string, int>("Sassenage",38360),
                new KeyValuePair<string, int>("Satolas-et-Bonce",38290),
                new KeyValuePair<string, int>("Savas-Mépin",38440),
                new KeyValuePair<string, int>("Séchilienne",38220),
                new KeyValuePair<string, int>("Semons",38260),
                new KeyValuePair<string, int>("Septème",38780),
                new KeyValuePair<string, int>("Sérézin-de-la-Tour",38300),
                new KeyValuePair<string, int>("Sermérieu",38510),
                new KeyValuePair<string, int>("Serpaize",38200),
                new KeyValuePair<string, int>("Serre-Nerpol",38470),
                new KeyValuePair<string, int>("Seyssinet-Pariset",38170),
                new KeyValuePair<string, int>("Seyssins",38180),
                new KeyValuePair<string, int>("Seyssuel",38200),
                new KeyValuePair<string, int>("Siccieu-Saint-Julien-et-Carisieu",38460),
                new KeyValuePair<string, int>("Siévoz",38350),
                new KeyValuePair<string, int>("Sillans",38590),
                new KeyValuePair<string, int>("Sinard",38650),
                new KeyValuePair<string, int>("Soleymieu",38460),
                new KeyValuePair<string, int>("La Sône",38840),
                new KeyValuePair<string, int>("Sonnay",38150),
                new KeyValuePair<string, int>("Sousville",38350),
                new KeyValuePair<string, int>("Succieu",38300),
                new KeyValuePair<string, int>("Susville",38350),
                new KeyValuePair<string, int>("Têche",38470),
                new KeyValuePair<string, int>("Tencin",38570),
                new KeyValuePair<string, int>("La Terrasse",38660),
                new KeyValuePair<string, int>("Theys",38570),
                new KeyValuePair<string, int>("Thodure",38260),
                new KeyValuePair<string, int>("Tignieu-Jameyzieu",38230),
                new KeyValuePair<string, int>("Torchefelon",38690),
                new KeyValuePair<string, int>("La Tour-du-Pin",38110),
                new KeyValuePair<string, int>("Le Touvet",38660),
                new KeyValuePair<string, int>("Tramolé",38300),
                new KeyValuePair<string, int>("Treffort",38650),
                new KeyValuePair<string, int>("Tréminis",38710),
                new KeyValuePair<string, int>("Trept",38460),
                new KeyValuePair<string, int>("La Tronche",38700),
                new KeyValuePair<string, int>("Tullins",38210),
                new KeyValuePair<string, int>("Valbonnais",38740),
                new KeyValuePair<string, int>("Valencin",38540),
                new KeyValuePair<string, int>("Valencogne",38730),
                new KeyValuePair<string, int>("La Valette",38350),
                new KeyValuePair<string, int>("Valjouffrey",38740),
                new KeyValuePair<string, int>("Varacieux",38470),
                new KeyValuePair<string, int>("Varces-Allières-et-Risset",38760),
                new KeyValuePair<string, int>("Vasselin",38890),
                new KeyValuePair<string, int>("Vatilieu",38470),
                new KeyValuePair<string, int>("Vaujany",38114),
                new KeyValuePair<string, int>("Vaulnaveys-le-Bas",38410),
                new KeyValuePair<string, int>("Vaulnaveys-le-Haut",38410),
                new KeyValuePair<string, int>("Vaulx-Milieu",38090),
                new KeyValuePair<string, int>("Velanne",38620),
                new KeyValuePair<string, int>("Vénérieu",38460),
                new KeyValuePair<string, int>("Venon",38610),
                new KeyValuePair<string, int>("Venosc",38520),
                new KeyValuePair<string, int>("Vernas",38460),
                new KeyValuePair<string, int>("Vernioz",38150),
                new KeyValuePair<string, int>("La Verpillière",38290),
                new KeyValuePair<string, int>("Le Versoud",38420),
                new KeyValuePair<string, int>("Vertrieu",38390),
                new KeyValuePair<string, int>("Veurey-Voroize",38113),
                new KeyValuePair<string, int>("Veyrins-Thuellin",38630),
                new KeyValuePair<string, int>("Veyssilieu",38460),
                new KeyValuePair<string, int>("Vézeronce-Curtin",38510),
                new KeyValuePair<string, int>("Vienne",38200),
                new KeyValuePair<string, int>("Vif",38450),
                new KeyValuePair<string, int>("Vignieu",38890),
                new KeyValuePair<string, int>("Villard-Bonnot",38190),
                new KeyValuePair<string, int>("Villard-de-Lans",38250),
                new KeyValuePair<string, int>("Villard-Notre-Dame",38520),
                new KeyValuePair<string, int>("Villard-Reculas",38114),
                new KeyValuePair<string, int>("Villard-Reymond",38520),
                new KeyValuePair<string, int>("Villard-Saint-Christophe",38119),
                new KeyValuePair<string, int>("Villefontaine",38090),
                new KeyValuePair<string, int>("Villemoirieu",38460),
                new KeyValuePair<string, int>("Villeneuve-de-Marc",38440),
                new KeyValuePair<string, int>("Ville-sous-Anjou",38150),
                new KeyValuePair<string, int>("Villette-d'Anthon",38280),
                new KeyValuePair<string, int>("Villette-de-Vienne",38200),
                new KeyValuePair<string, int>("Vinay",38470),
                new KeyValuePair<string, int>("Virieu",38730),
                new KeyValuePair<string, int>("Viriville",38980),
                new KeyValuePair<string, int>("Vizille",38220),
                new KeyValuePair<string, int>("Voiron",38500),
                new KeyValuePair<string, int>("Voissant",38620),
                new KeyValuePair<string, int>("Voreppe",38340),
                new KeyValuePair<string, int>("Vourey",38210)
        };
    }
}
